name: Auto Format
on:
  push:
    branches: [main]
jobs:
  autoformat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install StyLua
        run: |
          curl -LO https://github.com/JohnnyMorganz/StyLua/releases/download/v0.20.0/stylua-linux-x86_64.zip
          unzip -d /usr/local/bin stylua-linux-x86_64.zip
      - name: Run Stylua
        run: stylua .
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Fix formatting"
          add: "*.lua"
