name: Format
on: [pull_request]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: StyLua
        uses: JohnnyMorganz/stylua-action@v4.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: v4.0.0
          # CLI arguments
          args: --check .
